// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Note {
    /**
     * Creates a new Note instance.
     * @param {Partial<Note>} [$$source = {}] - The source object to create the Note.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("user_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user_id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("bgColor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bgColor"] = "";
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }
        if (!("pos_x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pos_x"] = 0;
        }
        if (!("pos_y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pos_y"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updated_at"] = 0;
        }
        if (!("deleted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["deleted"] = false;
        }
        if (!("synced" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["synced"] = false;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("vector_clock" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vector_clock"] = "";
        }
        if (!("timerDeadline" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timerDeadline"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Note}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Note(/** @type {Partial<Note>} */($$parsedSource));
    }
}
