// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class UserInfo {
    /**
     * Creates a new UserInfo instance.
     * @param {Partial<UserInfo>} [$$source = {}] - The source object to create the UserInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("picture" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["picture"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserInfo(/** @type {Partial<UserInfo>} */($$parsedSource));
    }
}
