// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auth$0 from "./auth/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./models/models.js";

/**
 * @param {string} userID
 * @returns {$CancellablePromise<models$0.Note | null>}
 */
export function CreateNote(userID) {
    return $Call.ByID(3901296041, userID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNote(id) {
    return $Call.ByID(3639942098, id);
}

/**
 * @returns {$CancellablePromise<auth$0.UserInfo | null>}
 */
export function GetCurrentUser() {
    return $Call.ByID(3403755359).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} userID
 * @returns {$CancellablePromise<models$0.Note[]>}
 */
export function GetNotes(userID) {
    return $Call.ByID(4001444448, userID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<auth$0.UserInfo | null>}
 */
export function Login() {
    return $Call.ByID(3243219574).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(2224079927);
}

/**
 * @param {string} userID
 * @returns {$CancellablePromise<void>}
 */
export function RestoreWindows(userID) {
    return $Call.ByID(1823505754, userID);
}

/**
 * @param {string} noteID
 * @param {boolean} pinned
 * @returns {$CancellablePromise<void>}
 */
export function SetAlwaysOnTop(noteID, pinned) {
    return $Call.ByID(3204375758, noteID, pinned);
}

/**
 * @param {string} userID
 * @returns {$CancellablePromise<void>}
 */
export function SyncNow(userID) {
    return $Call.ByID(1584298638, userID);
}

/**
 * @param {models$0.Note} note
 * @returns {$CancellablePromise<void>}
 */
export function UpdateNote(note) {
    return $Call.ByID(163960476, note);
}

// Private type creation functions
const $$createType0 = models$0.Note.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = auth$0.UserInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
